### ISSUE TITLE
No Layer / Total with Prusa-Slicer, "LayerDisplay" works

### ISSUE THREAD

**Issue by chatelao** [OllisGit/OctoPrint-DisplayLayerProgress#102]
Problem:
- The Layer stats show -/- with DisplayLaye.rProgress

The alternative plugin "LayerDisplay" (and the built-in gCode Overview) work both fine:
- https://plugins.octoprint.org/plugins/layerdisplay/

The gCode used is here:
- https://gist.github.com/chatelao/563d919a3bbb4ee29c6314c0b0bcf2fb

**Comment by OllisGit** [comment]
Hi @chatelao ,

what layer-indicator and what layer-expression (plugin-settings) do you use? Could find it in your g-code.
Please look into the readme from the start-page.

**Comment by chatelao** [comment]
Dear @OllisGit I just installed it "as-it-is". But will have a look at the Readme again.

**Comment by OllisGit** [comment]
@chatelao 
Sorry, was a typo: ```Couldn't find...```
You need to add this information in your slicer, like this:
![image](https://user-images.githubusercontent.com/24205767/71555154-f541a580-2a28-11ea-81a0-1cc480c6d844.png)
After that, everything should work out of the box.

**Comment by chatelao** [comment]
An API from the Code, just exposing the same numbre would be great. Let's as Gina, I will be back, if there is a simple answer.

**Comment by OllisGit** [comment]
Hi @chatelao!
I didn't get it! What do you mean?

There is an REST-API to get all values, read the [developer-section](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress#developer---section) from the readme.md!

**Comment by chatelao** [comment]
Hi @OllisGit , I just wondered if you could get the layer information from the OctoPrint core, instead of analyzing yourself. - This would remove (move to core) the dependency to the slicer.

**Comment by OllisGit** [comment]
Hi @chatelao unfortunately this is not possible, because octoprint doesn't provide such an api to get the necessary informations. 

Yes, there is the clientside javascript based GCode-Viewer, but there is also no hook to catch the layer information.
One option could be to grap the layerInfo from the bottom gcodeviewer-legend and parse that text, but in my option this is a hack and also this box show not always the correct layer information.
Only the slicers knows the exact layer-infos!
