### ISSUE TITLE
Help , Any guide for add layer-indicator in Simplify3D?

### ISSUE THREAD

**Issue by Askeshine** [OllisGit/OctoPrint-DisplayLayerProgress#120]
Hi , any have guide for add layer-indicator in Simplify3D i read alot of and i dont have chance...

![imagen](https://user-images.githubusercontent.com/37356127/74790756-56526080-5297-11ea-87fc-8545af35813f.png)

GCODE: 

![imagen](https://user-images.githubusercontent.com/37356127/74790775-65d1a980-5297-11ea-857e-8473cb1270fa.png)

**Comment by OllisGit** [comment]
Hi @Askeshine ,
hmmm...actually you don't need a separate "layer change script', because Simplify3D already create "layer-comments" like this ```; layer 1, Z = 0.100```.

Please look into the DLP plugin-settings / Layer, there must be this entry:
```1		[; layer ([0-9]+),.*]		Simplify3D```

If you could not find an error, please attach your uploaded gcode (directly from slicer + downloaded from octoprint, small button) and also your "layer-expressions" to this issue.

**Comment by OllisGit** [comment]
No feedback
