### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by goldjunge91** [OllisGit/OctoPrint-DisplayLayerProgress#121]
hi

can you create better explained examples? I do not understand how I have to set it for simplify3d that it works properly

**Comment by OllisGit** [comment]
see #120 , it is related to simplify3d. 
Short: your slicer needs to generate for each layer-change a comment in your gcode. E.g. Cura ddid this out-of-the-box. I think simplify3d does this as well. 
Look into your gcode and try to identify the layer-comments.

If you still have issues to setup your slicer, then attach your gcode to issue #120.

I closed this issue, because it is duplicated.
