### ISSUE TITLE
Wrong Total Height

### ISSUE THREAD

**Issue by CyberExplorer** [OllisGit/OctoPrint-DisplayLayerProgress#152]
If I download calibration cube from thingverse and slice it cura its shows correct 20mm height. But even simplest parts from solidworks and cura then displaylayerprogress and all other plugins using value from DLP is wrong. By the way cura shows correct height.

I send a sample.

[Test.zip](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/4705197/Test.zip)

**Comment by CyberExplorer** [comment]
![image](https://user-images.githubusercontent.com/828247/83321512-f9cced00-a258-11ea-923f-ed580d73ee9c.png)

**Comment by CyberExplorer** [comment]
Its almost finished part. Only 2 layer left but still shows wrong height. Actual part height is 5mm.

**Comment by OllisGit** [comment]
Hi @CyberExplorer,
I looked into your GCode and the Object is only ~5mm height.
I used http://gcode.ws/
![image](https://user-images.githubusercontent.com/24205767/83334867-b3ec4500-a2a9-11ea-8223-7793a3d12c27.png)
The model info in gcode.ws shows only 15mm, instead of 20mm.

I imported the gcode to Cuar4.5.0 and I can only see a 5mm object.
![image](https://user-images.githubusercontent.com/24205767/83335111-bf8c3b80-a2aa-11ea-8306-a7d709459d26.png)

If you look into the gcode via texteditor, you find the last layer in at ```Z4.9``` in line 15340. 
DLP shows ```5.5```, because after the last layer there is an other relative z-movement +0.5.

This is wrong, should be ```5.4``` no idea why.

But, please verify your model. Maybe you printed/downloaded the wrong Cube.

**Comment by CyberExplorer** [comment]
You misunderstand me. If I download a calibration cube from thingverse everything is fine. 20x20x20 cube shows 20mm on cura and your plugin. There is no problem with that.

But if I export my designs from solidworks as STL. And slice it Cura then the problem begin. Cura show correct height. Like in screenshot its show 5mm. But DLP show it 15mm. And Job Progress is wrong to because of layer height.

![image](https://user-images.githubusercontent.com/828247/83340371-cda87f00-a2df-11ea-8ca6-8f33bad08fcb.png)

**Comment by OllisGit** [comment]
ahh..okay!
Which method do you use for evaluating the height?

![image](https://user-images.githubusercontent.com/24205767/84476204-17a14580-ac8e-11ea-913e-8cc56dc87aba.png)

Maybe you need to switch to the second option to read the correct value from the gcode. Because there is a movement higher then the object itself.

**Comment by OllisGit** [comment]
no feedback. assumption: it works now.
