### ISSUE TITLE
Layer offset option not working

### ISSUE THREAD

**Issue by ilium007** [OllisGit/OctoPrint-DisplayLayerProgress#161]
Hi - I have noticed that the layer offset option does not increase layer offset in the uploaded gcode file as expected.

OctoPrint: 1.4.0
DisplayLayerProgress Plugin: 1.22.1 

<img width="525" alt="image" src="https://user-images.githubusercontent.com/732766/88468454-5ed65380-cf27-11ea-95ff-f8ecdc2f43f2.png">

Resulting gcode:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/732766/88468458-6f86c980-cf27-11ea-99a0-36f62b41ece4.png">

I tried changing to 2 and the resulting gcode layer still shows 0

**Comment by OllisGit** [comment]
Hi @ilium007 ,

thats the correct behaviour! The Offset is only used for the Display/UI and APIs.

The reason why I add the M117 indicator to the uploaded gcode is, because during printing OctoPrint doesn't provide the gcode comments to the plugin-processor. The processor can only handle real gcode.

More details can be found in my wiki: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/wiki/How-does-the-plugin-works

Hope that answers your question
Olli

PS. Why do you need to reflect the offset to the gcode?
