### ISSUE TITLE
rename plugin in pip list

### ISSUE THREAD

**Issue by RogierSchuring** [OllisGit/OctoPrint-DisplayLayerProgress#168]
Hi OllisGit,

I do not know if it's possible for you and how much work it would be, but could you rename the plugin so that it will have the same naming convention as the other octoprint plugins while doing a pip list?

Currently:
python -m pip list|grep Disp
DisplayLayerProgress          1.23.0

Others:
python -m pip list|grep OctoPrint
OctoPrint                     1.4.2
OctoPrint-Dashboard           1.14.0
OctoPrint-ExcludeRegionPlugin 0.2.0
OctoPrint-FileCheck           2020.8.7
OctoPrint-FirmwareCheck       2020.6.22
OctoPrint-OpiTemp             1.0.8
OctoPrint-PrintTimeGenius     2.2.5
OctoPrint-Telegram            1.5.2

This way it's easier to automate octoprint deployment and plugin installation.

Thanks!

**Comment by OllisGit** [comment]
Hi @RogierSchuring ,

the result of my pip list looks like this and it includes a lot of other plugins not using such naming-pattern.
![image](https://user-images.githubusercontent.com/24205767/91338005-8ba2b280-e7d4-11ea-9da0-7e8352fcad1e.png)

I will not do it, because I don't see the benefit and also the risk is high that I broke thousand of current installations, sorry!

**Comment by blueflame2020** [comment]
Okay, I understand. I will work around this in my automation :)

**Comment by RogierSchuring** [comment]
Okay, I understand. I will work around this in my automation then :)
