### ISSUE TITLE
Max Height not calculated when files sent directly from Slic3r

### ISSUE THREAD

**Issue by jackmang** [OllisGit/OctoPrint-DisplayLayerProgress#181]
Related to #166 
I'm using the latest release DisplayLayerProgress Plugin (1.24.0)
When I print in OP, I typically send the files directly from Slic3r which works great.  When I do this with your plug-in everything works except for total height.  I find that it displays the total height as "-".
I reviewed bug #166 and found the mention of dragging the gcode from explorer and dropping into OP.  I tried that and it works properly.
Directly sent from Slic3r:
![image](https://user-images.githubusercontent.com/1836536/97094462-c628a000-1609-11eb-9bbc-fcb3cf73b508.png)

Drag and dropped same Slic3r file from Explorer to OP:
![image](https://user-images.githubusercontent.com/1836536/97094335-14896f00-1609-11eb-83ea-c2d2550d8d26.png)

In both cases if I download the resulting gcode from OP I get an identical file.
gcode attached.
[test.gcode.txt](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/files/5433845/test.gcode.txt)

**Comment by jackmang** [comment]
I just did additional testing and I'm not getting a consistent result.  Before I waste your time let me do some additional confirmations to see if I can find a pattern.  I'll close this and resubmit if and when I have more to report.

**Comment by moogster** [comment]
Did you ever sort this issue out?

**Comment by OllisGit** [comment]
fyi: the max height value is provided by octoprint and the value is normaly calculated in the background (if not deactivated "never"), see plugin-settings:
![image](https://user-images.githubusercontent.com/24205767/138092390-52db8c98-50d1-4b42-9e6c-175ce24e9cdc.png)
Sometimes..when you use bigger models...the value is not shown, because it take some time. So you need to wait select an other file and reselect the file again.
