### ISSUE TITLE
Status bar font color

### ISSUE THREAD

**Issue by PederSa** [OllisGit/OctoPrint-DisplayLayerProgress#62]
Hi!
Wishlist:
Enable possibility to alter font color on status bar. 
(e.g. when choosing orange color on the status bar the text from this plugin becomes hard to read)
:)

**Comment by OllisGit** [comment]
Hi @PederSa ,
I am back from a long vacation and now I can support you with your issue.

Maybe I will implement this feature together with issue #51 ("add css-styles")

BR
Olli

**Comment by OllisGit** [comment]
Hi @PederSa 
I released a new Version 1.7.2 and in the default nav-bar pattern now includes a style element.
If you want to add color to your font, just add: `style="color:red;"`

BR
Olli

**Comment by PederSa** [comment]
Excellent!!!
Thanks
I’ll try it out and give feedback

BR //Peder

24 okt. 2018 kl. 23:09 skrev OllisGit <notifications@github.com<mailto:notifications@github.com>>:


Hi @PederSa<https://github.com/PederSa>
I released a new Version 1.7.2 and in the default nav-bar pattern now includes a style element.
If you want to add color to your font, just add: style="color:red;"

BR
Olli

**Comment by OllisGit** [comment]
The style-Attribute is a CSS-Property. 

So, if you want to change the appearance/color, just enter something like this:
`Progress: <span style='color:white; display: inline-block;width:24px;'>[progress]%</span>`

Or if you want to change the full text-color then wrap all the text-pattern in a separate span-element:

`<span style='color:white;'> Progress: <span style=display: inline-block; .... </span>`

**Comment by PederSa** [comment]
Really Great, Thanks!!

After learning some css style I ended up in this code:
<span style="color:white;font-weight:bold">Fan:[fanspeed]%</span>
<span style="color:white;font-weight:bold;padding-left:40px">Layer:[current_layer]/[total_layers]</span>
<span style="color:white;font-weight:bold;padding-left:40px;padding-right:80px">Progress:[progress]%</span>

And that gives me a great toolbar :)
![octoprint](https://user-images.githubusercontent.com/34133001/49186219-44b82c80-f364-11e8-958f-c20cc89863b3.png)

**Comment by Kpapadak1** [comment]
Thanks for the code edit to change the color. It works but I think it would be a good feature update to make a drop down menu or option to make the changes.  not everyone knows how to make these kind of changes.

**Comment by OllisGit** [comment]
@Kpapadak1 good idea, but I think a simple dropdown is not enough (font-color, size, style, background, ...).
But I added a documentation-hint in Version 1.8.1 with a link to this issue, so that someone else need to change the color he/she can look at @PederSa  comment.

**Comment by David-Maisonave** [comment]
I recommend that by default, the original text in the Navigable field has the color style included, so that uses can easily realized that the color can be changed, without having to read "Issue#62".
Example:
Progress:<span style='color:blue;display: inline-block;width:40px;'>[progress]%</span>
Layer:<span style='color:blue;display: inline-block;width:70px;'>[current_layer] of [total_layers]</span>
Height:<span style='color:blue;display: inline-block;width:130px;'>[current_height]mm of [total_height]mm</span>

Note: I also recommend that Layer and Height content be included in one <span>, so that there's not a big gap between "of" and second variable.  This also makes it easier for users to read the source text.
