### ISSUE TITLE
Miscalculated progress

### ISSUE THREAD

**Issue by pandel** [OllisGit/OctoPrint-DisplayLayerProgress#69]
Hey!

Many thanks for your plugin. Normally, it is working as expected. But now I have a very big print that seems to be totally miscalculated. I'll show you some pictures:

Print time left, Printed and percentage are obviously wrong (static text in German, sorry):
![dlpp-error](https://user-images.githubusercontent.com/12460002/53160266-de8c2000-35c7-11e9-8fb6-a0e90944c89c.jpg)

You can see from the screenshot, the print is in the upper third of the print, so I'd expect the plugin to say something about 75% done and the other values accordingly.
![dlpp-proove](https://user-images.githubusercontent.com/12460002/53160267-de8c2000-35c7-11e9-8dca-6182f12688e6.jpg)

Slicer is Simplify3D. What can I do to find out, what is going on here?

Regards,
Holger

**Comment by pandel** [comment]
Just for the record: I kept an eye on it today and there really seems to be a bug somewhere. That's what I get now and the print will be ready in a few minutes (layer count is correct):

![dlpp-error](https://user-images.githubusercontent.com/12460002/53181354-b0263900-35f7-11e9-89c3-400e502e1640.jpg)

**Comment by OllisGit** [comment]
Well, I am using the "orig." progress-value from OctoPrint and not a calculated value related to Layers.

Please look at the following forum-question and also the explanation from Gina in the YT-Clip.
https://community.octoprint.org/t/how-does-octoprint-calculate-progress/1265

Maybe I should add a hint in the Settings-Dialog...or even better: add a new key like `[layer-percentage]`, so that the user could decide which value he wants to see (progress or layer percentage).

What do you thing?

**Comment by pandel** [comment]
Very interesting thread, I understand better now. I don't think that it is your turn to change something at this point. I even think about trying out gcodestat. Most of the time estimates are pretty close to what the printer is doing actually. Only if the files are extremely large (complicated, large object or many objects) the estimates are way off. So it is Octoprint's problem, not yours.

Many thanks for taking time to answer!

Regards,
Holger
